function H = model(m1,m2,weight)

    N = size(m1,1);
    
    x1 = m1(:,1);
    y1 = m1(:,2);
    x2 = m2(:,1);
    y2 = m2(:,2);
    w  = weight(1:N);
    
    A = zeros(2*N, 9);
    
    % odd rows: 2*i-1
    A(1:2:end, :) = [ ...
        w .* x1, ...
        w .* y1, ...
        w, ...
        zeros(N,3), ...
        -w .* x2 .* x1, ...
        -w .* x2 .* y1, ...
        -w .* x2 ];
    
    % even rows: 2*i
    A(2:2:end, :) = [ ...
        zeros(N,3), ...
        w .* x1, ...
        w .* y1, ...
        w, ...
        -w .* y2 .* x1, ...
        -w .* y2 .* y1, ...
        -w .* y2 ];

    % 使用 SVD 分解矩阵 A
    [~, ~, V] = svd(A,0);

    % 单应性矩阵 H 是 V 的最后一列，重新排列为 3x3 矩阵
    H = reshape(V(:, end), 3, 3)';

    % 归一化 H，使其最后一个元素为 1
    H = H / H(3, 3);
    
end